import type { Metadata } from "next";
import { Navbar } from "./components/navbar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center flex-col ">
        <Navbar />
        <div className="w-full h-full flex justify-center items-center min-h-[calc(100vh-56px)]">
        {children}
        </div>
      </body>
    </html>
  );
}
